baseURL = "https://blog.phantom.tc/"
defaultContentLanguage = "tr"
theme = "terminal"
pagination.pagerSize = 5

[markup.goldmark.renderer]
  unsafe = true

[params]
  contentTypeName = "posts"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = false
  themeColor = "green"
  showLastUpdated = true
  showLanguageSelector = true

[languages]
  [languages.tr]
    languageName = "Türkçe"
    title = "Phantom-WireGuard Blog"
    subtitle = "Kendi Sunucun. Kendi Ağın. Kendi Gizliliğin."
    keywords = "wireguard, vpn, privacy, self-hosted, ghost-mode, multihop"
    copyright = "© 2025 Rıza Emre ARAS"
    menuMore = "Daha fazla"
    readMore = "Devamını oku"
    readOtherPosts = "Diğer yazıları oku"
    weight = 1

    [languages.tr.params.logo]
      logoText = "phantom-wireguard"
      logoHomeLink = "/"

    [languages.tr.menu]
      [[languages.tr.menu.main]]
        identifier = "about"
        name = "Hakkında"
        pageRef = "/about"
        weight = 1
      [[languages.tr.menu.main]]
        identifier = "posts"
        name = "Yazılar"
        pageRef = "/posts"
        weight = 2
      [[languages.tr.menu.main]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/ARAS-Workspace/phantom-wireguard"
        weight = 3

  [languages.en]
    languageName = "English"
    title = "Phantom-WireGuard Blog"
    subtitle = "Your Server. Your Network. Your Privacy."
    keywords = "wireguard, vpn, privacy, self-hosted, ghost-mode, multihop"
    copyright = "© 2025 Rıza Emre ARAS"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    weight = 2

    [languages.en.params.logo]
      logoText = "phantom-wireguard"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        pageRef = "/about"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        pageRef = "/posts"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/ARAS-Workspace/phantom-wireguard"
        weight = 3